kind: Pod
apiVersion: v1
metadata:
  name: emacs
  labels:
    app: emacs
spec:
  volumes:
    - name: git
      hostPath:
        type: DirectoryOrCreate
        path: /home/oonray/.git
    - name: ssh
      hostPath:
        type: DirectoryOrCreate
        path: /home/oonray/.ssh
  containers:
    - name: emacs
      image: oonray/dev:v1.0.41
      tty: true
      stdin: true
      env:
        - name: TERM
          value: xterm-256color
      volumeMounts:
        - mountPath: /home/oonray/.git
          name: git
        - mountPath: /home/oonray/.ssh
          name: ssh
