kind: Pod
apiVersion: v1
metadata:
  name: emacs
  labels:
    app: emacs
spec:
  volumes:
    - name: git
      hostPath:
        type: DirectoryOrCreate
        path: /home/oonray/.git
  containers:
    - name: emacs
      image: oonray/dev:v1.0.34
      tty: true
      stdin: true
      volumeMounts:
        - mountPath: /home/oonray/.git
          name: git
